import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora Product List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.sidebar}>
          <p className={styles.sidebar__title}>Filters</p>
          <div className={styles.sidebar__selects}>
            <select name="products" id="products" defaultValue="">
              <option value="" disabled>
                Product
              </option>
              <option value="product-name">Product 2</option>
            </select>
            <select name="state" id="state" defaultValue="">
              <option value="" disabled>
                State
              </option>
              <option value="state">State 2 test</option>
            </select>
            <select name="city" id="city" defaultValue="">
              <option value="" disabled>
                City
              </option>
              <option value="city">City 2</option>
            </select>
          </div>
        </div>

        <div className={styles.content}>
          <h1 className={styles.companyTitle}>Edvora</h1>
          <h2 className={styles.title}>Products</h2>

          <div className={styles.productList}>
            <h3 className={styles.productList__title}>Product Name</h3>
            <div className={styles.productList__wrapper}>
              <div className={styles.productList__content}>
                <div className={styles.productList__content__upper}>
                  <div>
                    <Image
                      src="https://png.pngtree.com/png-clipart/20190920/original/pngtree-chemical-glass-product-illustration-png-image_4626884.jpg"
                      alt="Product Name"
                      width={76}
                      height={79}
                    />
                  </div>
                  <div>
                    <p className={styles.productList__content__upper__name}>
                      Product Name
                    </p>
                    <p>Brand Name</p>
                    <p className={styles.productList__content__upper__price}>
                      $ 29.99
                    </p>
                  </div>
                </div>
                <div className={styles.productList__content__center}>
                  <div
                    className={styles.productList__content__center__location}
                  >
                    <p>Location</p>
                  </div>
                  <div className={styles.productList__content__center__date}>
                    <p>Date:10/12/2021</p>
                  </div>
                </div>
                <div className={styles.productList__content__bottom}>
                  <p>Description of the product</p>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </main>
    </div>
  );
}
